"""AgentRuntime — Microsoft Agent Framework SDK orchestrator.

Pipeline (shared by both streaming and non-streaming paths):

  1. Resolve conversation ownership:
       a. If thread_id was client-provided: the conversation MUST already exist
          for this user (routes.py already validated this, but we guard
          defensively).  If not found, abort with a clear error.
       b. If thread_id was auto-generated by AgentSession: create the
          conversation record now (backward-compatible flow for callers that
          do not pre-create via POST /conversations).
  2. Persist user message → receive MessageRecord with reserved sequence number
  3. RETRIEVE — hybrid Azure AI Search (keyword + VectorizedQuery)
  4. GATE — abort if evidence count or avg score is below threshold
  5. Get or create AF session (keyed by thread_id)
     └─ Cold-start: load Cosmos history BEFORE the just-saved user message
        (using before_sequence filter) and inject once via CosmosHistoryProvider.
        This prevents the current question from appearing in both the injected
        history block and the active user prompt.
     └─ Warm session: skip history injection; InMemoryHistoryProvider already
        has the in-process turn history.
  6. Inject pre-retrieved results via RagContextProvider
  7. GENERATE via Agent Framework ChatAgent (streaming internally, always)
  8. Emit structured citations from retrieval results (no text-pattern gating)
  9. Persist assistant message + citations

run_stream()  — wraps the pipeline and yields SSE-formatted strings.
run_once()    — wraps the pipeline and returns a plain dict (no SSE).
               Used by POST /chat so the route never parses SSE text.

Cold-start / warm session logging:
  The log lines "cold-start" vs "warm" make it easy to verify in production
  that history injection only fires once per thread per process lifetime.

Multi-user isolation:
  Ownership of the client-supplied thread_id is validated in routes.py before
  the runtime is invoked.  The runtime additionally guards defensively so that
  even without the route-level check, a missing conversation for the current
  user causes a clean abort rather than silently creating a shadow record.
  Message history is loaded via get_messages_for_user() which enforces both
  conversation ownership and per-user message filtering.
"""

from __future__ import annotations

import asyncio
import logging
import re
import time
from collections import OrderedDict
from collections.abc import AsyncGenerator
from typing import Optional

from agent_framework import AgentSession as AFAgentSession

from app.agent_runtime.citation_provider import build_citations
from app.agent_runtime.history_context_provider import format_history_block
from app.agent_runtime.intent_classifier import INTENT_CONDENSATION, classify_intent
from app.agent_runtime.query_rewriter import rewrite_query
from app.agent_runtime.session import AgentSession
from app.api.schemas import Citation, CitationsPayload
from app.auth.identity import UserIdentity
from app.config.settings import (
    COSMOS_HISTORY_MAX_TURNS,
    DEBUG_MODE,
    LLM_TIMEOUT_SECONDS,
    MIN_AVG_SCORE,
    MIN_RERANKER_SCORE,
    MIN_RESULTS,
    TOP_K,
    TRACE_MODE,
)
from app.llm.af_agent_factory import af_agent, history_provider, rag_provider
from app.storage import chat_store
from app.storage.cosmos_client import is_storage_enabled
from app.storage.models import MessageRecord
from app.tools.retrieval_tool import retrieve

logger = logging.getLogger(__name__)

# Emit a keepalive ping every N seconds to prevent proxy / browser SSE timeout.
_PING_INTERVAL_SECONDS = 20

# Patterns that indicate the LLM declined to answer from the provided context.
# When these appear in the generated answer, citations should be suppressed
# because the documents are not actually relevant to the question.
_REFUSAL_PATTERNS = re.compile(
    r"(?:^|\. )"  # Only at start of answer or start of a sentence (not after comma)
    r"(?:"
    r"I (?:cannot|can't|am unable to|could not|couldn't) (?:answer|find|locate|provide|determine)"
    r"|(?:the |this )?(?:context|retrieved|provided) (?:blocks? )?(?:do(?:es)? not|doesn't|don't) contain"
    r"|no relevant information (?:was |is )?found"
    r"|(?:this (?:question|topic) is )?(?:outside|beyond) the scope"
    r"|not (?:covered|addressed|mentioned) in (?:the |these )?(?:context|manuals?|documents?)"
    r"|I don't have (?:enough|sufficient) (?:information|context|evidence)"
    r"|(?:unfortunately|however),? I (?:cannot|can't|could not|couldn't|don't have|do not have)"
    r"|the (?:provided |given )?(?:documents?|manuals?|context) (?:do(?:es)? not|doesn't) (?:contain|include|address|cover)"
    r")",
    re.IGNORECASE,
)


def _is_refusal(answer: str) -> bool:
    """Return True if the LLM answer indicates it could not answer the question.

    Uses sentence-boundary-aware regex to avoid false positives like
    'This is not related to transformer oil testing' in a valid answer.
    """
    return bool(_REFUSAL_PATTERNS.search(answer))


def _filter_cited_results(answer: str, results: list[dict]) -> tuple[str, list[dict]]:
    """Filter to only cited results and renumber references in the answer.

    The LLM uses [N] notation to reference context blocks (1-indexed).
    We parse those references, keep only the cited results, and renumber
    the references so they match the filtered list.

    Example: LLM cites [3] and [5] out of 5 chunks.
      - Filtered results: [chunk3, chunk5]
      - Answer text: [3] -> [1], [5] -> [2]
      - Sources shown: Source [1], Source [2]

    Returns (renumbered_answer, filtered_results).
    """
    # Only match refs in valid range (1..len(results)) to avoid false
    # positives like [2024] (year) or [404] (error code).
    max_ref = len(results)
    all_matches = re.findall(r"\[(\d+)\]", answer)
    refs = sorted(set(int(m) for m in all_matches if 1 <= int(m) <= max_ref))
    if not refs:
        return answer, results

    cited = [(orig_idx, r) for orig_idx, r in enumerate(results) if (orig_idx + 1) in refs]

    if not cited:
        return answer, results

    # Build old-number -> new-number mapping
    renumber_map: dict[int, int] = {}
    filtered = []
    for new_idx, (orig_idx, r) in enumerate(cited, start=1):
        renumber_map[orig_idx + 1] = new_idx
        filtered.append(r)

    # Renumber references in the answer text
    def _renumber(match: re.Match) -> str:
        old_num = int(match.group(1))
        new_num = renumber_map.get(old_num)
        if new_num is not None:
            return f"[{new_num}]"
        if 1 <= old_num <= max_ref:
            return ""  # Remove uncited in-range refs
        return match.group(0)  # Preserve out-of-range numbers like [2024]

    renumbered = re.sub(r"\[(\d+)\]", _renumber, answer)
    # Clean up double spaces left by removed references
    renumbered = re.sub(r"  +", " ", renumbered)

    if TRACE_MODE:
        logger.info(
            "TRACE | citation_filter: LLM cited %s out of %d chunks -> showing %d | renumber: %s",
            refs, len(results), len(filtered), renumber_map,
        )

    return renumbered, filtered

# Canned response for the confidence gate failure.
_INSUFFICIENT_EVIDENCE_MSG = (
    "I don't have enough evidence from the technical manuals to answer "
    "your question confidently.\n\n"
    "Could you provide more detail — for example, the equipment name, "
    "model number, or the specific procedure you are looking for?"
)

# Canned response when the requested conversation is not found for this user.
# Intentionally does not reveal whether the thread exists for another user.
_THREAD_NOT_FOUND_MSG = (
    "Conversation not found. "
    "Please start a new chat or check that the correct conversation is selected."
)

# Per-process LRU cache of Agent Framework sessions, keyed by thread_id.
# InMemoryHistoryProvider stores turn history in each AFAgentSession.state for
# the lifetime of the process.  On cold start (process restart or new thread),
# Cosmos history is injected once by CosmosHistoryProvider.
# OrderedDict is used so that actively-used sessions are moved to the end
# and the least-recently-used session is evicted when the cache is full.
_af_sessions: OrderedDict[str, AFAgentSession] = OrderedDict()
_AF_SESSION_MAX_SIZE = 500  # evict LRU entries when cache exceeds this


# ---------------------------------------------------------------------------
# SSE encoding helpers
# ---------------------------------------------------------------------------

def _sse_data(payload: str) -> str:
    """Encode a string as an SSE data line.

    Newlines in *payload* are escaped to ``\\n`` so SSE's blank-line event
    boundary is never confused with content.  The frontend decodes them back.
    """
    return f"data: {payload.replace(chr(10), chr(92) + 'n')}\n\n"


def _sse_event(event_name: str, payload: str) -> str:
    """Encode a named SSE event.

    Newlines in *payload* are escaped to ``\\n`` so SSE's blank-line event
    boundary is never confused with content.  JSON payloads (like citations)
    should not contain raw newlines so this is safe for all callers.
    """
    escaped = payload.replace(chr(10), chr(92) + "n")
    return f"event: {event_name}\ndata: {escaped}\n\n"


# ---------------------------------------------------------------------------
# Pipeline helpers
# ---------------------------------------------------------------------------

def _compute_gate(results: list[dict]) -> tuple[float, float, bool]:
    """Return (avg_effective_score, gate_threshold, has_reranker).

    When the semantic reranker is active, scores are on the 0–4 scale and we
    gate on MIN_RERANKER_SCORE.  Otherwise we use base RRF/hybrid scores and
    gate on MIN_AVG_SCORE.
    """
    has_reranker = bool(results) and results[0].get("reranker_score") is not None
    if has_reranker:
        avg = sum(r.get("reranker_score") or 0 for r in results) / len(results)
        return avg, MIN_RERANKER_SCORE, True
    avg = sum(r["score"] for r in results) / len(results) if results else 0.0
    return avg, MIN_AVG_SCORE, False


async def _resolve_conversation(
    thread_id: str,
    user_id: str,
    user_name: str,
    client_provided: bool,
) -> bool:
    """Ensure a conversation record exists for (thread_id, user_id).

    Returns True if the pipeline may continue, False if it should abort.

    Behavior:
      - client_provided=True:  the conversation MUST already exist for this
        user.  If not found, log a warning and return False.  (routes.py
        should have caught this first; this is a defensive second layer.)
      - client_provided=False: the thread_id was auto-generated by AgentSession.
        If the conversation does not exist yet, create it now.  This preserves
        backward compatibility for callers that do not pre-create via
        POST /conversations.
    """
    conv = await chat_store.get_conversation(thread_id, user_id)

    if conv is not None:
        logger.info(
            "AgentRuntime: conversation resolved | thread=%s user=%s turns=%d",
            thread_id, user_id, conv.message_count,
        )
        return True

    if client_provided:
        # Thread not found for this user — unauthorized access or stale ID.
        logger.warning(
            "AgentRuntime: client-provided thread_id not found for user — "
            "aborting | thread=%s user=%s",
            thread_id, user_id,
        )
        return False

    # Auto-generated thread_id — create the conversation record.
    created = await chat_store.create_conversation(thread_id, user_id, user_name)
    if created is None:
        logger.error(
            "AgentRuntime: failed to create conversation | thread=%s user=%s",
            thread_id, user_id,
        )
        return False

    logger.info(
        "AgentRuntime: conversation auto-created | thread=%s user=%s",
        thread_id, user_id,
    )
    return True


async def _get_or_create_af_session(
    thread_id: str,
    user_id: str,
    current_user_msg: Optional[MessageRecord],
) -> AFAgentSession:
    """Return the AF session for thread_id, hydrating history on cold start.

    Cold-start behavior:
      - A new AFAgentSession is created.
      - Prior Cosmos messages are loaded using get_messages_for_user() with
        before_sequence to exclude the just-persisted user message.  This
        guarantees the current question never appears in both the injected
        history block and the active prompt.
      - get_messages_for_user() validates conversation ownership before
        querying and filters results by user_id, so history can only ever
        be loaded for the conversation's owning user.

    Warm session behavior:
      - The existing AFAgentSession is returned as-is.
      - InMemoryHistoryProvider already holds the in-process turn history.
      - No Cosmos history is loaded or injected.
    """
    existing = _af_sessions.get(thread_id)
    if existing is not None:
        # Move to end so this session is treated as most-recently-used.
        _af_sessions.move_to_end(thread_id)
        logger.info(
            "AgentRuntime: warm session reused | thread=%s", thread_id
        )
        return existing

    # Cold start — create fresh AF session
    af_session = af_agent.create_session()

    # Evict least-recently-used entry if the cache is full.
    if len(_af_sessions) >= _AF_SESSION_MAX_SIZE:
        lru_key, _ = _af_sessions.popitem(last=False)
        logger.info("AgentRuntime: evicted LRU session from cache | evicted=%s", lru_key)

    _af_sessions[thread_id] = af_session
    logger.info("AgentRuntime: cold-start — new AF session | thread=%s", thread_id)

    if not is_storage_enabled():
        return af_session

    # Determine sequence boundary so the current user question is excluded
    before_seq: Optional[int] = None
    if current_user_msg is not None:
        before_seq = current_user_msg.sequence
        logger.info(
            "AgentRuntime: cold-start history will exclude seq>=%d (current user msg) | thread=%s",
            before_seq, thread_id,
        )

    # get_messages_for_user validates ownership and filters by user_id
    prior = await chat_store.get_messages_for_user(
        thread_id,
        user_id,
        max_turns=COSMOS_HISTORY_MAX_TURNS,
        before_sequence=before_seq,
    )

    if prior:
        block = format_history_block(prior)
        history_provider.store_history_block(af_session, block)
        logger.info(
            "AgentRuntime: injected %d prior message(s) into cold-start session "
            "(before_seq=%s) | thread=%s",
            len(prior), before_seq, thread_id,
        )
    else:
        logger.info(
            "AgentRuntime: no prior history to inject (before_seq=%s) | thread=%s",
            before_seq, thread_id,
        )

    return af_session


async def _buffer_llm_response(
    question: str,
    af_session: AFAgentSession,
) -> tuple[str, bool]:
    """Run the LLM and buffer all streamed tokens.

    Returns (answer_text, had_error).  Uses stream=True internally so the
    code path is identical to run_stream(); only the delivery mechanism
    differs (buffered vs. yielded).
    """
    buf: list[str] = []
    had_error = False
    try:
        timeout = LLM_TIMEOUT_SECONDS if LLM_TIMEOUT_SECONDS > 0 else None
        async with asyncio.timeout(timeout):
            async for update in af_agent.run(question, stream=True, session=af_session):
                if update.text:
                    buf.append(update.text)
    except TimeoutError:
        logger.error("LLM generation timed out after %ss during buffered run", LLM_TIMEOUT_SECONDS)
        had_error = True
    except Exception:
        logger.exception("LLM generation failed during buffered run")
        had_error = True
    return "".join(buf), had_error


async def _persist_assistant(
    thread_id: str,
    user_id: str,
    answer_text: str,
    citations: list[Citation],
    had_error: bool = False,
) -> None:
    """Persist the assistant message and citations to Cosmos."""
    if not is_storage_enabled() or not answer_text:
        return
    status = "error" if had_error else "complete"
    citations_dicts = [c.model_dump() for c in citations]
    await chat_store.append_assistant_message(
        thread_id, user_id, answer_text, citations=citations_dicts, status=status
    )
    logger.info(
        "AgentRuntime: assistant message persisted | thread=%s citations=%d status=%s",
        thread_id, len(citations_dicts), status,
    )


# ---------------------------------------------------------------------------
# AgentRuntime
# ---------------------------------------------------------------------------

class AgentRuntime:
    """Orchestrates the retrieve → gate → generate → cite → persist pipeline.

    Public API:
      run_stream()  — async generator yielding SSE strings (for /chat/stream).
      run_once()    — coroutine returning a plain dict   (for /chat).

    Both paths share the same business logic; only the delivery layer differs.
    """

    async def run_once(
        self,
        question: str,
        session: AgentSession,
        identity: UserIdentity,
        top_k: int = TOP_K,
    ) -> dict:
        """Run the full pipeline and return the result as a plain dict.

        Returns
        -------
        dict with keys:
          answer       — generated answer text
          citations    — list of citation dicts
          thread_id    — the thread/conversation ID
          session_id   — alias for thread_id (backward compat)
        """
        user_id = identity.user_id
        user_name = identity.user_name
        thread_id = session.session_id

        logger.info(
            "AgentRuntime.run_once | thread=%s user=%s auth=%s | question=%s",
            thread_id, user_id, identity.auth_source, question[:120],
        )

        # ── 1. Resolve conversation ownership ─────────────────────────────
        if is_storage_enabled():
            ok = await _resolve_conversation(
                thread_id, user_id, user_name, session.client_provided
            )
            if not ok:
                await _persist_assistant(thread_id, user_id, _THREAD_NOT_FOUND_MSG, [])
                return {
                    "answer": _THREAD_NOT_FOUND_MSG,
                    "citations": [],
                    "thread_id": thread_id,
                    "session_id": thread_id,
                }

        # ── 2. Persist user message BEFORE generation ──────────────────────
        user_msg: Optional[MessageRecord] = None
        if is_storage_enabled():
            user_msg = await chat_store.append_user_message(thread_id, user_id, question)
            if user_msg is None:
                logger.error(
                    "AgentRuntime: failed to persist user message (CAS conflict or storage error) "
                    "— continuing without sequence tracking | thread=%s user=%s",
                    thread_id, user_id,
                )

        # -- 2a. Intent classification -- short-circuit non-questions ----
        has_history = user_msg is not None and user_msg.sequence > 1
        intent, canned = classify_intent(question, has_history=has_history)
        if canned is not None:
            logger.info(
                "Intent short-circuit | thread=%s intent=%s | question=%s",
                thread_id, intent, question,
            )
            await _persist_assistant(thread_id, user_id, canned, [])
            return {
                "answer": canned,
                "citations": [],
                "thread_id": thread_id,
                "session_id": thread_id,
            }

        # ── 2b. CONDENSATION: compress prior answer without re-retrieving ──
        # "give me in 5 steps", "summarize that", "shorter", "in one line" etc.
        # Load the last assistant answer from Cosmos and inject it directly into
        # the condensation instruction so the LLM knows exactly what to reformat
        # — even on cold start when InMemoryHistory is empty.
        if intent == INTENT_CONDENSATION:
            logger.info(
                "Intent CONDENSATION — skipping retrieval | thread=%s | question=%s",
                thread_id, question,
            )
            # Fetch the most recent assistant reply to include in the instruction
            prior_answer = ""
            if is_storage_enabled() and user_msg is not None:
                recent = await chat_store.get_messages_for_user(
                    thread_id, user_id, max_turns=2, before_sequence=user_msg.sequence,
                )
                for msg in reversed(recent):
                    if msg.role == "assistant" and msg.content:
                        prior_answer = msg.content
                        break

            af_session = await _get_or_create_af_session(thread_id, user_id, user_msg)
            rag_provider.store_results(af_session, [])
            rag_provider.store_condensation_mode(af_session, prior_answer=prior_answer)
            answer_text, had_error = await _buffer_llm_response(question, af_session)
            if had_error:
                err_append = "\n\nI'm sorry — an error occurred. Please try again."
                answer_text = (answer_text + err_append) if answer_text else err_append.strip()
            await _persist_assistant(thread_id, user_id, answer_text, [], had_error=had_error)
            return {
                "answer": answer_text,
                "citations": [],
                "thread_id": thread_id,
                "session_id": thread_id,
            }

        # ── 2c. Rewrite follow-up queries using conversation context ───────
        # Use only the last 4 messages (2 Q&A pairs) so the rewriter focuses on
        # the most recent topic and doesn't blend earlier unrelated topics.
        # search_query is used ONLY for retrieval — the LLM always receives the
        # original question so it answers the user's actual words, not a keyword phrase.
        search_query = question
        if is_storage_enabled() and user_msg is not None:
            recent = await chat_store.get_messages_for_user(
                thread_id, user_id, max_turns=4, before_sequence=user_msg.sequence,
            )
            if recent:
                search_query = await asyncio.to_thread(rewrite_query, question, recent)

        # ── 3. RETRIEVE ────────────────────────────────────────────────────
        try:
            results: list[dict] = await asyncio.to_thread(retrieve, search_query, top_k=top_k)
        except Exception:
            logger.exception("Retrieval failed | thread=%s", thread_id)
            err_msg = (
                "I'm sorry — an error occurred while searching the knowledge base. "
                "Please try again."
            )
            await _persist_assistant(thread_id, user_id, err_msg, [], had_error=True)
            return {"answer": err_msg, "citations": [], "thread_id": thread_id, "session_id": thread_id}

        # ── 4. GATE ────────────────────────────────────────────────────────
        avg_effective, gate_threshold, has_reranker = _compute_gate(results)

        if TRACE_MODE:
            logger.info(
                "TRACE | thread=%s n_results=%d avg_effective=%.4f "
                "gate=(>=%d results, >=%.3f) semantic_reranker=%s",
                thread_id, len(results), avg_effective,
                MIN_RESULTS, gate_threshold, has_reranker,
            )

        if len(results) < MIN_RESULTS or avg_effective < gate_threshold:
            # Log the specific reason(s) for gate failure
            reasons = []
            if len(results) < MIN_RESULTS:
                reasons.append(f"too_few_results({len(results)}<{MIN_RESULTS})")
            if avg_effective < gate_threshold:
                reasons.append(f"low_score({avg_effective:.4f}<{gate_threshold:.3f})")
            logger.warning(
                "Gate REJECTED | thread=%s reason=%s | n=%d avg=%.4f "
                "threshold_n=%d threshold=%.3f reranker=%s query=%r",
                thread_id, "+".join(reasons), len(results), avg_effective,
                MIN_RESULTS, gate_threshold, has_reranker,
                search_query[:120],
            )
            await _persist_assistant(thread_id, user_id, _INSUFFICIENT_EVIDENCE_MSG, [])
            return {
                "answer": _INSUFFICIENT_EVIDENCE_MSG,
                "citations": [],
                "thread_id": thread_id,
                "session_id": thread_id,
            }

        # ── 5. AF session (cold-start hydration with before_sequence) ──────
        af_session = await _get_or_create_af_session(thread_id, user_id, user_msg)

        # ── 6. Inject RAG results ──────────────────────────────────────────
        rag_provider.store_results(af_session, results)

        # ── 7. GENERATE (buffered) ─────────────────────────────────────────
        # Always pass the original question to the LLM — search_query (rewritten)
        # is only used for retrieval. The LLM must answer the user's actual words.
        answer_text, had_error = await _buffer_llm_response(question, af_session)

        if had_error:
            err_append = "\n\nI'm sorry — an error occurred while generating the answer. Please try again."
            answer_text = (answer_text + err_append) if answer_text else err_append.strip()

        # ── 8. CITE — suppress citations if LLM refused to answer ──────────
        if _is_refusal(answer_text):
            citations = []
        else:
            answer_text, cited_results = _filter_cited_results(answer_text, results)
            citations = build_citations(cited_results)

        # ── 9. Persist assistant message ───────────────────────────────────
        await _persist_assistant(thread_id, user_id, answer_text, citations, had_error=had_error)

        return {
            "answer": answer_text,
            "citations": [c.model_dump() for c in citations],
            "thread_id": thread_id,
            "session_id": thread_id,
        }

    async def run_stream(
        self,
        question: str,
        session: AgentSession,
        identity: UserIdentity,
        top_k: int = TOP_K,
    ) -> AsyncGenerator[str, None]:
        """Execute the pipeline and yield SSE-formatted strings.

        Yields
        ------
        str
            SSE strings: token data lines, named events (citations, ping),
            and the final ``[DONE]`` sentinel.
        """
        user_id = identity.user_id
        user_name = identity.user_name
        thread_id = session.session_id

        logger.info(
            "AgentRuntime.run_stream | thread=%s user=%s auth=%s | question=%s",
            thread_id, user_id, identity.auth_source, question[:120],
        )

        # ── 1. Resolve conversation ownership ─────────────────────────────
        if is_storage_enabled():
            ok = await _resolve_conversation(
                thread_id, user_id, user_name, session.client_provided
            )
            if not ok:
                await _persist_assistant(thread_id, user_id, _THREAD_NOT_FOUND_MSG, [])
                yield _sse_data(_THREAD_NOT_FOUND_MSG)
                yield _sse_event("citations", CitationsPayload(citations=[]).model_dump_json())
                yield _sse_data("[DONE]")
                return

        # ── 2. Persist user message BEFORE generation ──────────────────────
        user_msg: Optional[MessageRecord] = None
        if is_storage_enabled():
            user_msg = await chat_store.append_user_message(thread_id, user_id, question)
            if user_msg is None:
                logger.error(
                    "AgentRuntime: failed to persist user message (CAS conflict or storage error) "
                    "— continuing without sequence tracking | thread=%s user=%s",
                    thread_id, user_id,
                )

        # -- 2a. Intent classification -- short-circuit non-questions ----
        has_history = user_msg is not None and user_msg.sequence > 1
        intent, canned = classify_intent(question, has_history=has_history)
        if canned is not None:
            logger.info(
                "Intent short-circuit | thread=%s intent=%s | question=%s",
                thread_id, intent, question,
            )
            await _persist_assistant(thread_id, user_id, canned, [])
            yield _sse_data(canned)
            yield _sse_event("citations", CitationsPayload(citations=[]).model_dump_json())
            yield _sse_data("[DONE]")
            return

        # ── 2b. CONDENSATION: compress prior answer without re-retrieving ──
        # "give me in 5 steps", "summarize that", "shorter", "in one line" etc.
        # Load the last assistant answer from Cosmos and inject it directly into
        # the condensation instruction so the LLM knows exactly what to reformat.
        if intent == INTENT_CONDENSATION:
            logger.info(
                "Intent CONDENSATION — skipping retrieval | thread=%s | question=%s",
                thread_id, question,
            )
            # Fetch the most recent assistant reply to include in the instruction
            prior_answer = ""
            if is_storage_enabled() and user_msg is not None:
                recent = await chat_store.get_messages_for_user(
                    thread_id, user_id, max_turns=2, before_sequence=user_msg.sequence,
                )
                for msg in reversed(recent):
                    if msg.role == "assistant" and msg.content:
                        prior_answer = msg.content
                        break

            af_session = await _get_or_create_af_session(thread_id, user_id, user_msg)
            rag_provider.store_results(af_session, [])
            rag_provider.store_condensation_mode(af_session, prior_answer=prior_answer)
            last_ping_at = time.monotonic()
            answer_buf: list[str] = []
            stream_error = False
            try:
                timeout = LLM_TIMEOUT_SECONDS if LLM_TIMEOUT_SECONDS > 0 else None
                async with asyncio.timeout(timeout):
                    async for update in af_agent.run(question, stream=True, session=af_session):
                        now = time.monotonic()
                        if now - last_ping_at >= _PING_INTERVAL_SECONDS:
                            yield _sse_event("ping", "keepalive")
                            last_ping_at = now
                        if update.text:
                            answer_buf.append(update.text)
                            yield _sse_data(update.text)
            except TimeoutError:
                stream_error = True
                yield _sse_data("\n\n---\n\n*Response timed out. Please try again.*")
            except Exception as exc:
                stream_error = True
                err_detail = f" ({type(exc).__name__}: {exc})" if DEBUG_MODE else ""
                yield _sse_data(f"\n\nError generating response.{err_detail}")
            finally:
                condensed = "".join(answer_buf)
                await _persist_assistant(thread_id, user_id, condensed, [], had_error=stream_error)
                yield _sse_event("answer_replaced", condensed)
                yield _sse_event("citations", CitationsPayload(citations=[]).model_dump_json())
                yield _sse_data("[DONE]")
            return

        # ── 2c. Rewrite follow-up queries using conversation context ───────
        # Use only the last 4 messages (2 Q&A pairs) so the rewriter focuses on
        # the most recent topic and doesn't blend earlier unrelated topics.
        # search_query is used ONLY for retrieval — the LLM always receives the
        # original question so it answers the user's actual words, not a keyword phrase.
        search_query = question
        if is_storage_enabled() and user_msg is not None:
            recent = await chat_store.get_messages_for_user(
                thread_id, user_id, max_turns=4, before_sequence=user_msg.sequence,
            )
            if recent:
                search_query = await asyncio.to_thread(rewrite_query, question, recent)

        # ── 3. RETRIEVE ────────────────────────────────────────────────────
        try:
            results: list[dict] = await asyncio.to_thread(retrieve, search_query, top_k=top_k)
        except Exception:
            logger.exception("Retrieval failed | thread=%s", thread_id)
            err_msg = (
                "I'm sorry — an error occurred while searching the knowledge base. "
                "Please try again."
            )
            await _persist_assistant(thread_id, user_id, err_msg, [], had_error=True)
            yield _sse_data(err_msg)
            yield _sse_event("citations", CitationsPayload(citations=[]).model_dump_json())
            yield _sse_data("[DONE]")
            return

        # ── 4. GATE ────────────────────────────────────────────────────────
        avg_effective, gate_threshold, has_reranker = _compute_gate(results)

        if TRACE_MODE:
            logger.info(
                "TRACE | thread=%s n_results=%d avg_effective=%.4f "
                "gate=(>=%d results, >=%.3f) semantic_reranker=%s",
                thread_id, len(results), avg_effective,
                MIN_RESULTS, gate_threshold, has_reranker,
            )

        if len(results) < MIN_RESULTS or avg_effective < gate_threshold:
            reasons = []
            if len(results) < MIN_RESULTS:
                reasons.append(f"too_few_results({len(results)}<{MIN_RESULTS})")
            if avg_effective < gate_threshold:
                reasons.append(f"low_score({avg_effective:.4f}<{gate_threshold:.3f})")
            logger.warning(
                "Gate REJECTED | thread=%s reason=%s | n=%d avg=%.4f "
                "threshold_n=%d threshold=%.3f reranker=%s query=%r",
                thread_id, "+".join(reasons), len(results), avg_effective,
                MIN_RESULTS, gate_threshold, has_reranker, search_query[:120],
            )
            await _persist_assistant(thread_id, user_id, _INSUFFICIENT_EVIDENCE_MSG, [])
            yield _sse_data(_INSUFFICIENT_EVIDENCE_MSG)
            yield _sse_event("citations", CitationsPayload(citations=[]).model_dump_json())
            yield _sse_data("[DONE]")
            return

        # ── 5. AF session (cold-start hydration with before_sequence) ──────
        af_session = await _get_or_create_af_session(thread_id, user_id, user_msg)

        # ── 6. Inject RAG results ──────────────────────────────────────────
        rag_provider.store_results(af_session, results)

        # ── 7. GENERATE — stream tokens via Agent Framework ChatAgent ───────
        # Always pass the original question to the LLM — search_query (rewritten)
        # is only used for retrieval. The LLM must answer the user's actual words.
        last_ping_at = time.monotonic()
        answer_buf: list[str] = []
        stream_error = False
        client_disconnected = False
        try:
            timeout = LLM_TIMEOUT_SECONDS if LLM_TIMEOUT_SECONDS > 0 else None
            async with asyncio.timeout(timeout):
                async for update in af_agent.run(question, stream=True, session=af_session):
                    now = time.monotonic()
                    if now - last_ping_at >= _PING_INTERVAL_SECONDS:
                        yield _sse_event("ping", "keepalive")
                        last_ping_at = now

                    if update.text:
                        answer_buf.append(update.text)
                        yield _sse_data(update.text)

        except TimeoutError:
            logger.error("LLM streaming timed out after %ss | thread=%s", LLM_TIMEOUT_SECONDS, thread_id)
            stream_error = True
            # Use separator to visually distinguish the error from partial answer
            yield _sse_data(
                "\n\n---\n\n*Response generation timed out. The answer above may be incomplete. Please try again.*"
            )
        except GeneratorExit:
            # Client closed connection mid-stream (browser tab closed).
            # Fall through to finally block to persist partial answer.
            client_disconnected = True
            logger.info("Client disconnected mid-stream | thread=%s", thread_id)
        except Exception as exc:
            logger.exception("LLM streaming failed | thread=%s", thread_id)
            stream_error = True
            err_detail = f" ({type(exc).__name__}: {exc})" if DEBUG_MODE else ""
            yield _sse_data(
                "\n\nI'm sorry — an error occurred while generating the answer. "
                f"Please try again.{err_detail}"
            )
        finally:
            # ── 8. CITE + PERSIST — always runs, even on client disconnect ──
            # This ensures partial answers are saved to history.
            answer_text = "".join(answer_buf)
            if not answer_text:
                # Nothing to persist (empty LLM response)
                if not client_disconnected:
                    yield _sse_data("[DONE]")
                return

            if _is_refusal(answer_text):
                citations = []
            else:
                answer_text, cited_results = _filter_cited_results(answer_text, results)
                citations = build_citations(cited_results)

            status = "error" if stream_error else ("partial" if client_disconnected else "complete")
            await _persist_assistant(
                thread_id, user_id, answer_text, citations,
                had_error=stream_error or client_disconnected,
            )

            if not client_disconnected:
                yield _sse_event("answer_replaced", answer_text)
                yield _sse_event("citations", CitationsPayload(citations=citations).model_dump_json())
                yield _sse_data("[DONE]")

