"""AgentSession — lightweight per-request state carrier.
 
Created by the route, passed into AgentRuntime.run_stream(), and populated
as the pipeline executes. Nothing is persisted between requests (no DB yet).
 
client_provided:
    True  — the caller supplied a specific session_id (thread_id).
            AgentRuntime treats a missing conversation as an ownership error
            rather than silently auto-creating one.
    False — the session_id was auto-generated by AgentSession (default).
            AgentRuntime will create the conversation record on first use.
"""
 
import uuid
from dataclasses import dataclass, field
 
 
@dataclass
class AgentSession:
    """Holds the question and any state accumulated during agent execution."""
 
    question: str
    session_id: str = field(default_factory=lambda: str(uuid.uuid4()))
 
    # Set True by the route when the client explicitly provided a session_id.
    # Used by AgentRuntime to distinguish auto-generated IDs (safe to create)
    # from client-supplied IDs (must already exist for this user).
    client_provided: bool = False
 
    # Populated by AgentRuntime after retrieval
    retrieved_results: list[dict] = field(default_factory=list)
 
    # Populated by AgentRuntime after generation
    answer_text: str = ""
 
